token1 = "" # Токен пользователя 1
token2 = "" # Токен пользователя 2

chat_id1 = "1" # ID Чата пользователя 1
user_id1 = "1" # ID пользователя 2, которого будем добавлять от пользователя 1

chat_id2 = "1" # ID Чата пользователя 2
user_id2 = "1" # ID пользователя 1, которого будем добавлять от пользователя 2